const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1400, height: 1100 } });
  page.on('pageerror', err => console.log('PAGEERROR', err.message));
  await page.goto('http://localhost:5173/login', { waitUntil: 'load' });
  await page.waitForTimeout(500);
  await page.locator('input[type="email"], input[name="email"]').first().fill('studenthaianh@example.com');
  await page.locator('input[type="password"]').first().fill('test123@');
  await page.locator('button[type="submit"]').first().click();
  await page.waitForTimeout(2000);
  await page.goto('http://localhost:5173/student/planner', { waitUntil: 'load' });
  await page.waitForTimeout(2000);
  await page.getByText('Thêm tự học', { exact: false }).first().click();
  await page.waitForTimeout(500);
  await page.screenshot({ path: 'modal_open.png' });
  await page.locator('input[placeholder="Tự học"]').fill('Ôn tập CSI106');
  await page.locator('button:has-text("Lưu")').first().click();
  await page.waitForTimeout(1500);
  await page.screenshot({ path: 'after_add_block.png', fullPage: true });
  await browser.close();
})();
