-- Fix: 3 tables + 1 column missing on the Supabase dev DB, found 22/08 while
-- investigating a real 500 error on the Instructor Dashboard.
--
-- WHAT THIS FIXES: the Instructor Dashboard / risk alerts screens currently
-- crash with "column risk_signals.policy_version does not exist" because
-- 2 migrations that exist in this branch's code were never actually applied
-- to this Supabase database:
--   - migrations/versions/20260823_risk_policy_and_admin_settings.py
--   - migrations/versions/20260824_mock_lms_sync_versions.py
--
-- This script recreates exactly what those 2 migrations would have created,
-- as plain SQL, so it can be pasted into the Supabase Dashboard's SQL Editor
-- directly -- it does NOT touch Alembic's own version bookkeeping
-- (the `alembic_version` table), because that has a separate, already-known
-- problem (this DB's `alembic_version` points at a revision that belongs to
-- a different branch's history, not this one -- see PROJECT_CONTEXT.md
-- mục 9 ý8). Fixing that is a bigger, separate decision -- this script only
-- adds the specific tables/column that are missing, so the app stops
-- crashing. It is safe to run more than once (every step checks "does this
-- already exist?" first).
--
-- WHAT THIS DOES NOT DO: it does not fix the `alembic_version` mismatch
-- itself, so `alembic upgrade head`/`alembic current` run from a terminal
-- will still be confused about this DB's history. That is fine -- the app
-- itself does not use Alembic at runtime, only for one-time schema changes.
--
-- ============================================================================
-- HOW TO RUN THIS (step by step, no SQL knowledge assumed):
--   1. Open https://supabase.com/dashboard and select this project.
--   2. In the left sidebar, click "SQL Editor".
--   3. Click "+ New query".
--   4. Copy this ENTIRE file's contents and paste them into the editor.
--   5. Click "Run" (or press Ctrl+Enter).
--   6. You should see "Success. No rows returned" (or similar) at the
--      bottom -- that means it worked. If you see a red error message
--      instead, stop and share the exact error text before doing anything
--      else (do not re-run blindly).
--   7. To confirm the fix worked: reload the Cursus app, log in as an
--      instructor, and open the Instructor Dashboard -- it should load
--      without the "at-risk students" section silently showing 0 by error.
-- ============================================================================


-- 1) risk_policies: versioned risk-scoring policy (mục 14.1).
--    Seeds exactly one row (version 1) with the values risk_engine.py
--    hardcoded before this feature existed, so nothing about how risk
--    scoring behaves changes just from running this script.
CREATE TABLE IF NOT EXISTS risk_policies (
    policy_version INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    effective_from TIMESTAMP NOT NULL,
    signal_weights JSON NOT NULL,
    signal_thresholds JSON NOT NULL,
    severity_bands JSON NOT NULL,
    reason TEXT NOT NULL,
    rolled_back_from INTEGER,
    created_by VARCHAR REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL
);

INSERT INTO risk_policies
    (policy_version, effective_from, signal_weights, signal_thresholds, severity_bands, reason, rolled_back_from, created_by, created_at)
SELECT
    1,
    now(),
    '{"OVERDUE_TASKS_2_PLUS": 2, "COMPLETION_BELOW_40": 2, "TASK_DEFERRED_2_PLUS": 1, "DUE_WITHIN_48H_NOT_STARTED": 1, "INACTIVE_7_DAYS": 2}',
    '{"OVERDUE_TASKS_2_PLUS": 2, "COMPLETION_BELOW_40": 0.4, "TASK_DEFERRED_2_PLUS": 2, "DUE_WITHIN_48H_NOT_STARTED": 48}',
    '[[0, "normal", "LOW"], [3, "watch", "MEDIUM"], [5, "needs_support", "HIGH"]]',
    'Initial policy - seeded from pre-versioning hardcoded defaults (risk_rules_v1).',
    NULL,
    NULL,
    now()
WHERE NOT EXISTS (SELECT 1 FROM risk_policies WHERE policy_version = 1);

-- Keep the auto-increment counter consistent with the row we just seeded,
-- in case this table already existed with a different history.
SELECT setval(pg_get_serial_sequence('risk_policies', 'policy_version'), (SELECT MAX(policy_version) FROM risk_policies));


-- 2) risk_signals.policy_version: THE column actually causing the 500 error.
ALTER TABLE risk_signals
    ADD COLUMN IF NOT EXISTS policy_version INTEGER REFERENCES risk_policies(policy_version) ON DELETE SET NULL;


-- 3) admin_settings: per-organization Admin Console settings (demo mode /
--    auto risk alerts / default semester). Starts empty -- the app creates
--    a row for each org the first time it's read (same pattern as
--    guardrail rules), so no seed data needed here.
CREATE TABLE IF NOT EXISTS admin_settings (
    organization_id VARCHAR PRIMARY KEY REFERENCES organizations(id) ON DELETE CASCADE,
    demo_mode_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    auto_risk_alerts_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    default_semester VARCHAR NOT NULL DEFAULT 'Fall2026',
    updated_at TIMESTAMP NOT NULL,
    updated_by VARCHAR REFERENCES users(id) ON DELETE SET NULL
);


-- 4) mock_lms_sync_versions: Mock LMS sync history (mục 6.6). Starts empty --
--    "no sync has happened yet" is simply an empty table.
CREATE TABLE IF NOT EXISTS mock_lms_sync_versions (
    sync_version INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload JSON NOT NULL,
    reason TEXT NOT NULL,
    rolled_back_from INTEGER,
    created_by VARCHAR REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL
);
