"""Seed the 36 real courses into Mock LMS's own DB.

The 36-code list is the union of:
  - the 34 codes `real_curriculum_service.discover_real_course_codes()` returns in the
    main Cursus repo (unambiguous 1:1 catalog match with a parsed `chunks_<code>.json`,
    excluding the 8 combo/elective-slot files that don't map cleanly to one catalog code)
  - SSA101 and CSI106, which that function deliberately excludes because Cursus already
    ingests them through other existing paths (`gate2_demo`, `student_mock_data_service`) --
    but Mock LMS still needs to expose them since it doesn't know about those paths.

This list was generated by a one-off, read-only call to that function (not re-derived here
by guessing the combo-slot exclusion rule, to avoid drifting out of sync with the real
service). If the parsed chunk set ever changes, regenerate by running, from the repo root:

    python -c "from src.services.mock.real_curriculum_service import discover_real_course_codes as d; print(sorted(d()))"

and updating DISCOVERABLE_34 below (plus re-checking EXCLUDED_BUT_INCLUDED still applies).
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from app.db import Base, ENGINE, SessionLocal  # noqa: E402
from app.models import PlatformCourse  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[2]
CATALOG_PATH = REPO_ROOT / "docs" / "planning" / "v2" / "data" / "courses_BIT_SE_K20D_K21A.json"

DISCOVERABLE_34 = [
    "CEA201", "CSD201", "DBI202", "ENW493c", "EXE201", "HCM202", "IOT102", "ITE302c",
    "JPD113", "JPD123", "LAB211", "MAD101", "MAE101", "MAS291", "MLN111", "MLN122",
    "MLN131", "NWC204", "OJT202", "OSG202", "OTP101", "PMG201c", "PRF192", "PRJ301",
    "PRM393", "PRO192", "SSG105", "SWD392", "SWE202c", "SWP391", "SWR302", "VNR202",
    "WDU203c", "WED201c",
]
EXCLUDED_BUT_INCLUDED = ["SSA101", "CSI106"]
COURSE_CODES = sorted(DISCOVERABLE_34 + EXCLUDED_BUT_INCLUDED)


def main() -> None:
    catalog = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    by_code = {s["Subject Code"]: s for s in catalog["subjects"]}

    Base.metadata.create_all(bind=ENGINE)
    db = SessionLocal()
    try:
        created, updated = 0, 0
        for code in COURSE_CODES:
            subject = by_code.get(code)
            if not subject:
                print(f"  SKIP {code}: not found in catalog")
                continue
            course = db.get(PlatformCourse, f"course_{code.lower()}")
            if course is None:
                course = PlatformCourse(id=f"course_{code.lower()}", code=code)
                db.add(course)
                created += 1
            else:
                updated += 1
            course.name = subject["Subject Name"]
            course.semester = str(subject.get("Semester") or "")
            course.credit = int(subject.get("NoCredit") or 0)
        db.commit()
        print(f"Seeded {len(COURSE_CODES)} courses ({created} created, {updated} updated).")
    finally:
        db.close()


if __name__ == "__main__":
    main()
