import { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Bot, Send, X, FileText } from 'lucide-react';
import { streamCursusChat } from '../../lib/api';

export default function CursusChat({ user }) {
  const [open, setOpen] = useState(false); const [messages, setMessages] = useState([]); const [value, setValue] = useState(''); const [conversationId, setConversationId] = useState(null); const [loading, setLoading] = useState(false);
  if (user?.role !== 'student') return null;
  const send = async (event) => { event.preventDefault(); const text = value.trim(); if (!text || loading) return; setValue(''); setMessages((items) => [...items, { role: 'user', text }, { role: 'assistant', text: '', citations: [] }]); setLoading(true);
    try { await streamCursusChat({ message: text, conversationId, onEvent: (type, data) => { if (type === 'meta') setConversationId(data.conversationId); if (type === 'delta') setMessages((items) => items.map((item, i) => i === items.length - 1 ? { ...item, text: item.text + data.text } : item)); if (type === 'citation') setMessages((items) => items.map((item, i) => i === items.length - 1 ? { ...item, citations: data.items } : item)); if (type === 'error') setMessages((items) => items.map((item, i) => i === items.length - 1 ? { ...item, text: 'Cursus đang tạm thời không phản hồi. Hãy thử lại sau.' } : item)); } }); } finally { setLoading(false); } };
  return <><button aria-label="Mở Cursus" onClick={() => setOpen(true)} className="fixed bottom-5 right-5 z-[90] flex h-12 items-center gap-2 rounded-lg border border-accent bg-surface px-3 text-sm font-semibold text-fg shadow-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-accent"><Bot size={18}/> Cursus</button>
  {open && <aside aria-label="Cursus chat" className="fixed inset-y-0 right-0 z-[100] flex w-full max-w-[440px] flex-col border-l border-border bg-paper shadow-xl"><header className="flex items-center justify-between border-b border-border bg-surface px-5 py-4"><div><h2 className="font-serif text-lg text-ink">Cursus</h2><p className="text-xs text-ink-secondary">Trợ lý học tập có nguồn</p></div><button aria-label="Đóng Cursus" onClick={() => setOpen(false)}><X size={20}/></button></header><main className="flex-1 space-y-4 overflow-y-auto p-5">{messages.length === 0 && <p className="rounded-lg border border-border bg-surface p-4 text-sm text-ink-secondary">Bạn muốn biết gì về môn học, kế hoạch hoặc cách dùng Cursus?</p>}{messages.map((item, index) => <article key={index} className={item.role === 'user' ? 'ml-8 rounded-lg bg-accent-soft p-3 text-sm text-ink' : 'mr-4 rounded-lg border border-border bg-surface p-3 text-sm text-ink'}><ReactMarkdown remarkPlugins={[remarkGfm]}>{item.text || 'Đang soạn câu trả lời…'}</ReactMarkdown>{item.citations?.map((citation) => <div key={citation.id} className="mt-2 flex gap-2 border-t border-border pt-2 font-mono text-xs text-accent"><FileText size={14}/>{citation.title}{citation.section ? ` · ${citation.section}` : ''}</div>)}</article>)}</main><form onSubmit={send} className="border-t border-border bg-surface p-4"><textarea value={value} onChange={(e) => setValue(e.target.value)} placeholder="Hỏi Cursus…" className="min-h-20 w-full resize-none rounded-md border border-border bg-paper p-3 text-sm focus:outline-none focus:ring-2 focus:ring-accent"/><button disabled={loading} className="mt-2 inline-flex items-center gap-2 rounded-md bg-accent px-3 py-2 text-sm font-semibold text-white disabled:opacity-50"><Send size={15}/>Gửi</button></form></aside>}</>;
}
