import React, { useEffect, useState } from 'react';
import { CalendarClock } from 'lucide-react';
import { createInstructorClassException, getInstructorClassWeek } from '../../lib/api';
import Button from '../shared/Button';
import Modal from '../shared/Modal';

const monday = () => { const d = new Date(); d.setHours(0,0,0,0); d.setDate(d.getDate() - ((d.getDay() + 6) % 7)); return d.toISOString().slice(0,10); };

export default function InstructorClassSchedulePanel() {
  const [weekStart, setWeekStart] = useState(monday()); const [items, setItems] = useState([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [selected, setSelected] = useState(null); const [reason, setReason] = useState('');
  const load = async () => { try { const data = await getInstructorClassWeek(weekStart); setItems(data.items || []); } catch (err) { setError(err.message); } };
  useEffect(() => { load(); }, [weekStart]);
  const cancel = async () => { if (!selected || reason.trim().length < 3) return; setBusy(true); try { await createInstructorClassException({ schedule_id: selected.id.split(':')[1], section_id: selected.section_id, kind: 'CANCELLED', event_date: selected.start.slice(0,10), start_minute: new Date(selected.start).getHours()*60 + new Date(selected.start).getMinutes(), end_minute: new Date(selected.end).getHours()*60 + new Date(selected.end).getMinutes(), reason }); setSelected(null); setReason(''); await load(); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <div className="space-y-5 pb-12"><section className="card p-5"><div className="flex items-center gap-2"><CalendarClock className="text-accent" size={18}/><div><h1 className="text-lg font-bold text-fg">Lịch giảng dạy</h1><p className="text-xs text-fg-secondary">Chỉ các section bạn phụ trách. Hủy buổi luôn yêu cầu lý do và thông báo đến sinh viên.</p></div></div><input type="date" className="input mt-4 max-w-xs text-xs" value={weekStart} onChange={e=>setWeekStart(e.target.value)}/></section>{error && <p className="text-xs text-danger">{error}</p>}<section className="card divide-y divide-line">{items.map(item=><div key={item.id} className="flex items-center justify-between gap-3 p-4"><div><p className="font-mono text-xs font-bold text-fg">{item.course_code} · {item.title}</p><p className="mt-1 text-xs text-fg-secondary">{new Date(item.start).toLocaleString('vi-VN')} · {item.room || 'Chưa có phòng'} {item.kind === 'MAKEUP' ? '· Buổi bù' : ''}</p></div>{item.kind === 'CLASS' && <button className="text-xs font-bold text-danger" onClick={()=>setSelected(item)}>Hủy buổi</button>}</div>)}{items.length===0&&<p className="p-6 text-sm text-fg-muted">Không có buổi dạy trong tuần này.</p>}</section>{selected&&<Modal open onClose={()=>setSelected(null)} title={`Hủy buổi ${selected.course_code}`} footer={<><Button type="button" variant="outline" onClick={()=>setSelected(null)}>Đóng</Button><Button type="button" variant="primary" busy={busy} disabled={busy} onClick={cancel}>Xác nhận hủy</Button></>}><textarea required minLength="3" className="textarea text-sm" placeholder="Lý do hủy buổi" value={reason} onChange={e=>setReason(e.target.value)}/></Modal>}</div>;
}
