"""Baseline schema for Postgres (and other SQLAlchemy backends).

Revision ID: 20260808_baseline
Revises:
Create Date: 2026-08-08

Replaces the previous incomplete autogenerated chain (archived under
migrations/versions_legacy/). Creates the full application schema from
SQLAlchemy models.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

from src.db.models import Base

_BASELINE_TABLE_NAMES = frozenset(
    {
        "announcements",
        "assignment_overrides",
        "assignments",
        "audit_logs",
        "calendar_events",
        "course_prerequisites",
        "course_sections",
        "courses",
        "curriculum_versions",
        "daily_plans",
        "document_chunks",
        "documents",
        "enrollments",
        "guardrail_evaluation_cases",
        "guardrail_evaluation_results",
        "guardrail_events",
        "instructor_interventions",
        "learning_goals",
        "lessons",
        "mfa_recovery_codes",
        "mfa_totp_credentials",
        "mfa_trusted_devices",
        "modules",
        # Not "baseline" tables conceptually -- created here only because a baseline table's
        # live model already declares a FK to them, and create_all() needs the referenced
        # table to exist in the same call:
        #  - organizations: users/courses/programs/curriculum_versions.organization_id
        #    (owned by 20260812_organizations_and_tenancy.py, which no-ops its own creation
        #    once it sees this table already exists)
        #  - semester_setups: calendar_events.semester_setup_id
        #    (owned by 20260821_semester_practice.py, already guarded the same way)
        #  - risk_policies: risk_signals.policy_version
        #    (owned by 20260823_risk_policy_admin migration, guarded the same way)
        "organizations",
        "semester_setups",
        "risk_policies",
        "programs",
        "progress_events",
        "quiz_questions",
        "quizzes",
        "rag_evaluation_cases",
        "rag_evaluation_results",
        "reminder_deliveries",
        "reminders",
        "replan_proposals",
        "resource_access_events",
        "risk_signals",
        "rubric_criteria",
        "rubrics",
        "schedule_blocks",
        "sessions",
        "study_tasks",
        "submissions",
        "task_dependencies",
        "users",
        "verification_tokens",
        "weekly_plans",
        "weekly_reflections",
    }
)

# revision identifiers, used by Alembic.
revision: str = "20260808_baseline"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    tables = [Base.metadata.tables[name] for name in _BASELINE_TABLE_NAMES]
    Base.metadata.create_all(bind=bind, tables=tables)


def downgrade() -> None:
    bind = op.get_bind()
    tables = [Base.metadata.tables[name] for name in _BASELINE_TABLE_NAMES]
    Base.metadata.drop_all(bind=bind, tables=tables)
